In [2]:
import tensorflow as tf

In [3]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/",one_hot = True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [4]:
mnist

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000241BB9C7EF0>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000241BA931E10>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x00000241BA98E9B0>)

In [5]:
print(mnist.train.images.shape , mnist.train.labels.shape)
print(mnist.test.images.shape , mnist.test.labels.shape)
print(mnist.validation.images.shape , mnist.validation.labels.shape)
mnist.train.labels[0]

(55000, 784) (55000, 10)
(10000, 784) (10000, 10)
(5000, 784) (5000, 10)


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [6]:
with tf.Session() as sess :
    print(tf.random_normal([784,256]).eval())

[[ 0.71978515  1.2876306  -0.36072296 ... -1.011375    0.72044384
  -0.24227144]
 [ 0.9273274  -1.2060016  -0.5910101  ... -1.637249   -0.06270396
  -0.72818726]
 [-1.8091173  -1.3116473  -1.6563568  ...  0.24570183  1.3522321
   0.02035055]
 ...
 [ 0.9711389   1.6769863   0.81723255 ...  0.02775337  0.9579706
  -0.3969944 ]
 [ 1.7728772  -0.28677893 -1.0019287  ... -0.48161155 -0.16465978
  -0.18547879]
 [-0.31683868  1.2683002   1.2446811  ...  0.5713958   0.2587519
  -0.40096757]]


In [87]:
#weights and baises
n_input = 784
n_hidden_1 = 256
n_hidden_2 = 256
n_classes = 10

weights = {'h1': tf.Variable(tf.random_normal([n_input , n_hidden_1])),
           'h2': tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2])),
           'out': tf.Variable(tf.random_normal([n_hidden_2,n_classes]))
          
          }

baises = {'h1':tf.Variable(tf.random_normal([n_hidden_1])),
          'h2':tf.Variable(tf.random_normal([n_hidden_2])),
          'out':tf.Variable(tf.random_normal([n_classes]))
         }

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [88]:
def forward_propagation(x,weights,baises):
    input_h1 = tf.add(tf.matmul(x,weights['h1']),baises['h2'])
    out_h1 = tf.nn.relu(input_h1)
    
    input_h2 = tf.add(tf.matmul(out_h1 , weights['h2']) , baises['h2'])
    out_h2 = tf.nn.relu(input_h2)
    
    in_final_layer = tf.add(tf.matmul(out_h2, weights['out']),baises['out'])
    
    return in_final_layer  

In [89]:
x = tf.placeholder('float',[None, n_input])
y = tf.placeholder(tf.int32 ,[None , n_classes])

In [90]:
pred = forward_propagation(x,weights,baises)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = pred, labels = y))
optimizer = tf.train.AdamOptimizer(learning_rate = 0.01)
optimize = optimizer.minimize(cost)
sess.run(tf.global_variables_initializer())

In [91]:
# BATCH GRADIENT DECENT cost optimization
batch_size = 1000
for i in range(21):
    num_batches = int(mnist.train.num_examples/batch_size)
    total_cost = 0
    r=0
    for j in range(num_batches):
        r += 1000
        cost_ ,_ = sess.run([cost,optimize] , feed_dict = {x:mnist.train.images[r-1000:r], y:mnist.train.labels[r-1000:r]})
        total_cost += cost_
    print(total_cost)

8830.37573814392
1521.9158372879028
885.6358847618103
580.7494759559631
401.97440695762634
297.2341318130493
247.72549498081207
197.15268969535828
156.91229957342148
127.38610863685608
111.01910465955734
85.89672750234604
64.13280384242535
50.416738241910934
41.300014801323414
31.728983141481876
14.191006020177156
11.593852577052896
8.690532512985168
5.189031418076951
3.1081166123915


In [ ]:
# COST OPTIMAIZATION BY ITTERATION 
for i in range(55):
    sess.run([cost,optimize] , feed_dict = {x:mnist.train.images, y:mnist.train.labels})

In [92]:
# measuring pre correctness
predictions = tf.argmax(pred , 1)
true_labels = tf.argmax(y,1)
correct_predictions = tf.equal(predictions , true_labels)
p = sess.run(correct_predictions, feed_dict = {x:mnist.train.images, y:mnist.train.labels})

In [93]:
#RESULT
# total no of all true values / correct values 
p.sum()

54893

In [94]:
a = sess.run(predictions , feed_dict ={x:mnist.train.images})
print(a)
b = tf.argmax(mnist.train.labels , 1)
sess.run(b)

[7 3 4 ... 5 6 8]


array([7, 3, 4, ..., 5, 6, 8], dtype=int64)

In [53]:
mnist.train.images.shape[0]

55000